#!/usr/bin/env bash

set -eu

if [ "$#" -lt 1 ]
then
  >&2 echo "Easily add 'Co-authored-by' trailers to the commit template.

Usage:
  git co-author initials ..."
  exit 1
fi

if ! git config commit.template &> /dev/null
then
  >&2 echo "git commit template is not configured

Example:
    git config --global commit.template '~/.git-template'"
  exit 1
fi

for initials in "$@"
do
    if ! git config "co-authors.$initials" &> /dev/null
    then
      >&2 echo "initials '$initials' are not configured

Example:
    git config --global co-authors.aa 'Ann Author <ann.author@users.noreply.github.com>'"
      exit 1
    fi
done

token="Co-authored-by"
template_path=$(git config commit.template)
template_path="${template_path/#\~/$HOME}"  # Replace '~' with $HOME
temp_file=$(mktemp)

grep -v "$token" "$template_path" > "$temp_file"
mv "$temp_file" "$template_path"

for initials in "$@"
do
    value=$(git config "co-authors.$initials")
    git interpret-trailers --trailer "$token: $value" --in-place "$template_path"
done

git interpret-trailers --parse "$template_path"
