#!/usr/bin/env bash

set -eu

if ! git config commit.template &> /dev/null
then
  >&2 echo "git commit template is not configured

Example:
    git config --global commit.template '~/.git-template'"
  exit 1
fi

token="Co-authored-by"
template_path=$(git config commit.template)
template_path="${template_path/#\~/$HOME}"  # Replace '~' with $HOME

touch "$template_path"
sed -i '' "/$token/d" "$template_path"
