#!/usr/bin/env bash

set -eu

abort() {
  >&2 echo "$1"
  exit 1
}

usage() {
  abort "Easily add 'Co-authored-by' trailers to the commit template.

Usage:
  git co-author initials ...

Options:
  --help    Show help
  --clear   Remove all 'Co-authored-by' trailers"
}

if [ "$#" -eq 0 ]
then
  usage
fi

for arg in "$@"
do
  if [[ $arg = "--help" ]]
  then
    usage
  fi

  if [[ $arg = "-h" ]]
  then
    usage
  fi
done

if ! git config commit.template &> /dev/null
then
  abort "commit template is not configured

Example:
  git config --global commit.template '~/.git-template'"
fi

template_path=$(git config commit.template)
template_path="${template_path/#\~/$HOME}"  # Replace '~' with $HOME
touch "$template_path"

token="Co-authored-by"

clear_trailers() {
  sed -i '' "/$token/d" "$template_path"
}

print_trailers() {
  git interpret-trailers --parse "$template_path"
}

for arg in "$@"
do
  if [[ $arg = "--clear" ]]
  then
    clear_trailers
    print_trailers
    exit 0
  fi
done

for initials in "$@"
do
    if ! git config "co-authors.$initials" &> /dev/null
    then
      abort "co-author '$initials' is not configured

Example:
  git config --global co-authors.aa 'Ann Author <ann.author@example.com>'"
    fi
done

clear_trailers

for initials in "$@"
do
    value=$(git config "co-authors.$initials")
    git interpret-trailers --trailer "$token: $value" --in-place "$template_path"
done

print_trailers
